export default [
  {
    id: 1,
    name: "Taj Lake Palace",
    images: [
      {
        id: 1,
        src: "s1-img1.jpg",
        title: "Rajasthan",
        description: "Stunning clifftop villa overlooking the Aegean Sea",
      },
      {
        id: 2,
        src: "s1-img2.jpg",
        title: "Infinity Pool",
        description: "Three-tiered infinity pool with volcano views",
      },
      {
        id: 3,
        src: "s1-img3.jpg",
        title: "Luxury Interior",
        description: "Whitewashed interiors with modern amenities",
      },
    ],
    tag: "hotel",
    style: "Royal Heritage, Floating Palace",
    setting: "In the middle of Lake Pichola, surrounded by the Aravalli Hills",
    description:
      "A white marble dream that appears to float on water. Built in 1746, it's one of the most romantic hotels in the world, offering royal Rajput hospitality.",
    facilities: [
      "Yoga and pilates classes.",
      "books and films to borrow.",
      "WiFi throughout. In rooms.",
      "All ages are welcome",
      "Jacuzzi on each private terrace.",
      "Lounge by the three-tiered infinity pool.",
      "Get steamy in the marble hammam, or book a massage or facial in the treatment room.",
    ],
    price: 975,
  },
  {
    id: 2,
    name: "ITC Grand Chola",
    images: [
      {
        id: 1,
        src: "s2-img1.jpg",
        title: "Chennai",
        description: "Luxury ranch in the wilderness",
      },
      {
        id: 2,
        src: "s2-img2.jpg",
        title: "Mountain Views",
        description: "Breathtaking views of the surrounding mountains",
      },
      {
        id: 3,
        src: "s2-img3.jpg",
        title: "Ranch Activities",
        description: "Horseback riding and outdoor adventures",
      },
    ],
    tag: "hotel",
    style: "Dravidian Imperial",
    setting: "Wild Montana countryside",
    description:
      "One of the best Ayurvedic spa resorts in the world. Yoga, detox, meditation, and silence — it’s a soul reset.",
    facilities: [
      "Rodeo grounds (for the weekly rodeo).",
      "cinema.",
      "the Buckle Barn event space.",
      "library.",
      "bowling alley.",
      "Spa.",
      "The thousands of acres have room for a heated outdoor pool.",
    ],
    price: 870,
  },
  {
    id: 3,
    name: "The Oberoi Udaivilas",
    images: [
      {
        id: 1,
        src: "s3-img1.jpg",
        title: "Alpine Retreat Exterior",
        description: "Luxury ski chalet in the Austrian Alps",
      },
      {
        id: 2,
        src: "s3-img2.jpg",
        title: "Spa & Pool",
        description: "Heated pool and spa facilities with mountain views",
      },
      {
        id: 3,
        src: "s3-img3.jpg",
        title: "Ski Resort Access",
        description: "Direct access to world-famous Arlberg resort",
      },
    ],
    tag: "hotel",
    style: "Mewari Palace-style architecture",
    setting: "On the banks of Lake Pichola",
    description:
      "Lavish domes, peacocks in gardens, candlelit courtyards — a true royal fantasy that reflects Udaipur’s grandeur.",
    facilities: [
      "Heated ski lockers.",
      "wine cellar.",
      "children’s playroom.",
      "free WiFi throughout.",
      "laundry service.",
      "All ages are welcome",
      "Walled with thick timber, each suite has a glass-encased fireplace.",
      "The heated pool is in the spa area, and cuts a suave figure thanks to its slate-clad walls.",
    ],
    price: 346,
  },
  {
    id: 4,
    name: "Ananda in the Himalayas",
    images: [
      {
        id: 1,
        src: "s4-img1.jpg",
        title: "Tuscan Villa Exterior",
        description: "Restored ancient farmhouse in Tuscany",
      },
      {
        id: 2,
        src: "s4-img2.jpg",
        title: "Villa Interior",
        description: "Modern luxury meets traditional Italian charm",
      },
      {
        id: 3,
        src: "s4-img3.jpg",
        title: "Val d'Orcia Views",
        description: "Panoramic views from the infinity pool",
      },
    ],
    tag: "villa",
    style: "Wellness Retreat",
    setting: "Himalayan foothills, overlooking the Ganges",
    description:
      "One of the best Ayurvedic spa resorts in the world. Yoga, detox, meditation, and silence — it’s a soul reset.",
    facilities: [
      "In the TV room: 82-inch flatscreen TV with Apple TV. Playstation 4.",
      "Flatscreen TVs in all bedrooms.",
      "Free WiFi throughout.",
      "Smartphone-enabled sound-system.",
      "Coal barbecue, on request.",
      "Air-conditioning throughout.",
      "Two hours of housekeeping and turndown service daily.",
      "Welcome groceries on arrival.",
    ],
    price: 1125,
  },
  {
    id: 5,
    name: "The Leela Palace ",
    images: [
      {
        id: 1,
        src: "s5-img1.jpg",
        title: "Caldera Views",
        description: "Luxury villa overlooking Santorini's famous caldera",
      },
      {
        id: 2,
        src: "s5-img2.jpg",
        title: "Infinity Pool",
        description: "Three-tiered infinity pool at cliff's edge",
      },
      {
        id: 3,
        src: "s5-img3.jpg",
        title: "Wellness Terrace",
        description: "Private terraces with plunge pools and sunset views",
      },
    ],
    tag: "villa",
    style: "Contemporary Indian Luxury",
    setting: " Diplomatic enclave, Lutyens' Delhi",
    description:
      " Inspired by Indian palaces, this 5-star retreat blends Mughal architecture and modern opulence with rooftop pools and a view of Rashtrapati Bhavan.",
    facilities: [
      "This luxury stay’s buildings and outdoor living spaces are laid out over three levels.",
      "Fully equipped kitchen with wine- and gourmet-food-stocked Smeg refrigerator and a Nespresso coffee machines.",
      "Working floating fireplaces.",
      "A marble-lined spa with heated floors, a traditional hammam steam room, aromatherapy shower, treatment room and relaxation zone.",
      "Stocked wine cellar.",
      "The triangular, triple-tiered infinity pool is positioned at the edge of the cliff and looks out over the caldera.",
      "Two hours of housekeeping and turndown service daily.",
      "The pool has an underwater sound system; it’s unheated and ranges in depth from 1.60 to 1.90 metres.",
    ],
    price: 975,
  },
  {
    id: 6,
    name: "Isprava Villas ",
    images: [
      {
        id: 1,
        src: "s6-img1.jpg",
        title: "Ocean Villa Exterior",
        description: "Palatial villa in coconut plantation setting",
      },
      {
        id: 2,
        src: "s6-img2.jpg",
        title: "Private Pool",
        description: "25-metre heated pool with panoramic ocean views",
      },
      {
        id: 3,
        src: "s6-img3.jpg",
        title: "Luxury Interior",
        description: "Wood-lined interiors with floor-to-ceiling windows",
      },
    ],
    tag: "villa",
    style: "Mediterranean + Portuguese Colonial",
    setting: "Private locations near beaches or hills",
    description:
      "Celebrity-favorite, these are ultra-luxury, private villas with chefs, pools, tropical gardens — perfect for slow living and content creation.",
    facilities: [
      "The spacious villas (9,908sq m) come complete with a luxurious lounge, a media room, a library and a fully-equipped kitchen manned by a private chef; some also boast a gym, massage room and steam room.",
      "Enjoy the great outdoor views through floor-to-ceiling windows from the comfort of the wood-filled living space, decorated with luxe fabrics and perfectly positioned artworks and antiques.",
      "There are eight ocean-facing bedrooms, each with a king-size bed and an ensuite bathroom with a sunken bath tub and separate shower.",
      "Just a few steps from the living room, the 25-metre heated private pool has panoramic ocean views and is surrounded by sunbeds and 12 sunloungers.",
      "The living room leads out onto an expansive private terrace overlooking the ocean.",
      "The pool is the main focal point, but there are various outdoor dining and lounging salas to park yourself on.",
      "Two hours of housekeeping and turndown service daily.",
      "During high season (December to April), hotel transfers are free.",
    ],
    price: 900,
  },
];
